INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2000,'HIDDEN_CITIES','Europe','Italy','Rome Behind Locked Doors: Music, Magic, & Secret Crypts',3425,'Architectural wonders,History and mistery,Photography bomb',7,4.2,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2001,'CRUISING','Antarctica','Antarctica','Antarctica Classic',5471,'Ice & cold,Mother nature',9,3.9,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2002,'SCIENCE_AND_NATURE','Asia','Nepal','Everest Base Camp Trek',4611,'Biking and hiking,Mother nature,Ice & cold,In the mountains',18,4.5,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2003,'CRUISING','Europe','Norway','Cruise: Norwegian Fjords & Arctic Discovery',4331,'Mother nature,Ice & cold',15,5.0,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2004,'HISTORY_AND_CULTURE','Africa','Morocco','Morocco’s Mountains, Medinas, and Desert Oases',3190,'Ancient wonders,Photography bomb,Forever summer,Fascinating fauna,Architectural wonders',11,4.7,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2005,'HISTORY_AND_CULTURE','Asia','Iran','Ancient Persia, Modern Iran: Civilizations Old and New',4685,'Photography bomb,Ancient wonders',12,4.5,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2006,'HISTORY_AND_CULTURE','Asia','Mongolia','Wander Mongolia: Blue Skies and Endless Steppe',2990,'Biking and hiking,Photography bomb,Far far East,Fascinating fauna,Mother nature',12,3.7,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2007,'HIDDEN_CITIES','Europe','Spain','Barcelona Behind the Scenes: Cabaret and Carnival',3475,'Photography bomb',6,4.2,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2008,'SCIENCE_AND_NATURE','South America','Brazil','Brazilian Wildlife',4098,'Photography bomb,Fascinating fauna,Mother nature',9,5.0,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2009,'HIDDEN_CITIES','Asia','Jordan','Jordan: Lost City Of Arabia',2274,'Photography bomb,Architectural wonders,History and mistery',10,4.1,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2010,'SCIENCE_AND_NATURE','Africa','Rwanda','Gorillas in Africa''s Midst',6549,'Photography bomb,Fascinating fauna,Mother nature',13,3.5,null,null);
INSERT INTO TRIP (ID,CATEGORY,REGION,COUNTRY,TITLE,PRICE,TAGS,DURATION,RATING,DEPARTURE_DATE,END_DATE_TO_SIGN) VALUES (2011,'SCIENCE_AND_NATURE','Africa','Zambia','Wild Zambian Safari',6538,'Photography bomb,Fascinating fauna,Mother nature',11,4.8,null,null);

INSERT INTO USER(EMAIL, NAME, AGE, PASSWORD, COUNTRY, SEX, PROFESSION) VALUES ('jovcheska.aleksandra@yahoo.com', 'Aleksandra Jovcheska', 23, 'password', 'Macedonia', 'F', 'Student');
INSERT INTO USER(EMAIL, NAME, AGE, PASSWORD, COUNTRY, SEX, PROFESSION) VALUES ('jovcheska.vera@yahoo.com', 'Vera Jovcheska', 25, 'password123', 'Macedonia', 'F', 'Professor');
INSERT INTO USER(EMAIL, NAME, AGE, PASSWORD, COUNTRY, SEX, PROFESSION) VALUES ('jovcheska.valentina@yahoo.com', 'Valentina Jovcheska', 49, 'password789', 'Macedonia', 'F', 'Manager');