CREATE TABLE TRIP (

  ID NUMBER(19,0) NOT NULL,

  CATEGORY VARCHAR2 (40),
  REGION VARCHAR2 (40),
  COUNTRY VARCHAR2 (40),
  TITLE VARCHAR2(70),
  PRICE NUMBER (19,0),
  TAGS VARCHAR2 (150),
  DURATION NUMBER (5, 0),
  RATING DECIMAL (3, 0),
  DEPARTURE_DATE DATE,
  END_DATE_TO_SIGN DATE,

  PRIMARY KEY (ID)
);

CREATE TABLE USER (
  EMAIL VARCHAR2(30) NOT NULL,

  NAME VARCHAR2 (20),
  AGE NUMBER(19,0),
  PASSWORD VARCHAR2 (40) NOT NULL,
  COUNTRY VARCHAR2 (40),
  SEX VARCHAR2 (10),
  PROFESSION VARCHAR2 (40),
  TRAVEL_COMPANION VARCHAR2 (40),
  ENTERTAINMENT VARCHAR2 (40),
  TRIP_LENGTH VARCHAR2 (40),
  DESTINATION VARCHAR2 (40),

  PRIMARY KEY (EMAIL)
);

CREATE TABLE USER_TRIP (
  ID NUMBER(19,0) NOT NULL,
  USER_ID VARCHAR2(30),
  TRIP_ID NUMBER(19,0),

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(EMAIL),
  FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID)
);