CREATE TABLE TRIP (

  ID NUMBER(19,0) NOT NULL,

  CATEGORY VARCHAR2 (40),
  REGION VARCHAR2 (40),
  COUNTRY VARCHAR2 (40),
  TITLE VARCHAR2(70),
  PRICE NUMBER (19,0),
  TAGS VARCHAR2 (40),
  DURATION NUMBER (5, 0),
  STARS NUMBER (3, 0),
  BEEN_HERE NUMBER (5,0),
  WANT_TO_VISIT NUMBER (5,0),
  DEPARTURE_DATE DATE,
  END_DATE_TO_SIGN DATE,
  DESCRIPTION VARCHAR2 (40),

  PRIMARY KEY (ID)
);

CREATE TABLE USER (
  USERNAME VARCHAR2(30) NOT NULL,

  NAME VARCHAR2 (20),
  AGE NUMBER(19,0),
  PASSWORD VARCHAR2 (40) NOT NULL,
  COUNTRY VARCHAR2 (40),
  EMAIL VARCHAR2 (30),
  SEX VARCHAR2 (10),
  PROFESSION VARCHAR2 (40),

  PRIMARY KEY (USERNAME)
);

CREATE TABLE USER_TRIP (
  ID NUMBER(19,0) NOT NULL,
  USER_ID VARCHAR2(30),
  TRIP_ID NUMBER(19,0),

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(USERNAME),
  FOREIGN KEY (TRIP_ID) REFERENCES TRIP(ID)
);